### PR TITLE
Changed Bank Name for ifsc

### PR DESCRIPTION
**Pull request by rohitkeshwani07**

### CODE REVIEW

**Comment by captn3m0** [comment]
Merge after build passes.

**Comment by rohitkeshwani07** [comment]
should i change the release version in package.json?? 
not being used anywhere?

**Comment by captn3m0** [comment]
Not yet. We're planning a release soon, that will get taken care of separately.

**Comment by captn3m0** [comment]
Resolved in 1.3.3 release

**Pull request closed without merging**
