### PR TITLE
Update HTTPoison and ExVCR

### PR DESCRIPTION
**Pull request by nihalgonsalves**

### CODE REVIEW

**Comment by captn3m0** [comment]
@nihalgonsalves Looks like there is a new bank out because of a sublet change. I'll file a PR for that so we can merge this.

**Comment by captn3m0** [comment]
(Don't merge yet)

**Comment by captn3m0** [comment]
@nihalgonsalves I'll do a `1.2.0` release with the next RBI update? (Last version everywhere should be `1.1.8`, so I'll bump it to `1.2.0` for a minor version bump)

**Comment by nihalgonsalves** [comment]
Sorry, I actually did mean `1.2.0`. Don't know why I wrote that. Sounds good 👍

**Pull request merged**
