### PR TITLE
[ex] Add Hex wercker

### PR DESCRIPTION
**Pull request by nihalgonsalves**

### CODE REVIEW

**Comment by captn3m0** [comment]
Added the build, failed due to some hex dependency: https://app.wercker.com/Razorpay/ifsc/runs/elixir/5a82818a9fe1e000013547ab?step=5a82819eda96a80001a65f6c 

The project visibility is set to public, so you might have to create a wercker account to see the error.

Posting the error here as well:

```
source "/pipeline/script-a8cc1aac-a94e-42fa-bf76-e1a2e2b2a87f/run.sh" < /dev/null
Could not find Hex, which is needed to build dependency :poison
Shall I install Hex? (if running non-interactively, use "mix local.hex --force") [Yn] ** (Mix) Could not find an SCM for dependency :poison from IFSC.Mixfile
```

**Comment by nihalgonsalves** [comment]
I made an account and logged in. I can now see the overview page, but clicking on the Details link from the GitHub Status still returns this: "You are not authorized to view this pipeline execution". Can you manually authorise me? `nihalgonsalves` on Wercker.

**Comment by captn3m0** [comment]
@nihalgonsalves figuring out the access, here's the output till then.

```
==> exactor
Compiling 10 files (.ex)
Generated exactor app
==> ifsc
Could not find "rebar3", which is needed to build dependency :mimerl
I can install a local copy which is just used by Mix
Shall I install rebar3? (if running non-interactively, use "mix local.rebar --force") [Yn] ** (Mix) Could not find "rebar3" to compile dependency :mimerl, please ensure "rebar3" is available
```

**Comment by captn3m0** [comment]
@nihalgonsalves The build (scraper) keeps timing out, so the elixir pipeline hasn't run yet

**Comment by nihalgonsalves** [comment]
@captn3m0 still failing unfortunately, I tested the current setup locally in a Docker build, and it works fine. Can you check the permissions / share the latest output please?

```
Sending build context to Docker daemon  11.69MB
Step 1/8 : FROM elixir
latest: Pulling from library/elixir
f49cf87b52c1: Pull complete 
7b491c575b06: Pull complete 
b313b08bab3b: Pull complete 
51d6678c3f0e: Pull complete 
f78d9e0e21b3: Pull complete 
91a2115e0c6c: Pull complete 
ebc79c6d36c1: Pull complete 
26d46c189571: Pull complete 
Digest: sha256:1c23d112c503361196294a2737ddf2b7d8d574f47137577dbed8783c4854e51e
Status: Downloaded newer image for elixir:latest
 ---> 7aa702f5b940
Step 2/8 : RUN mkdir -p /usr/src/app/
 ---> Running in 8e2ae61225dd
Removing intermediate container 8e2ae61225dd
 ---> eec9cc05366e
Step 3/8 : WORKDIR /usr/src/app/
Removing intermediate container f21fcc146787
 ---> b8ba16d0feb8
Step 4/8 : RUN mix local.hex --force
 ---> Running in c2b79596fc58
* creating /root/.mix/archives/hex-0.17.3
Removing intermediate container c2b79596fc58
 ---> a54b0c1a9631
Step 5/8 : RUN mix local.rebar --force
 ---> Running in 1814f78f5130
* creating /root/.mix/rebar
* creating /root/.mix/rebar3
Removing intermediate container 1814f78f5130
 ---> 21e6a034eb24
Step 6/8 : ADD . .
 ---> 0960f6d72daf
Step 7/8 : RUN mix deps.get
 ---> Running in e7cdf7f830a9
Resolving Hex dependencies...
Dependency resolution completed:
  certifi 2.0.0
  earmark 1.2.4
  ex_doc 0.18.2
  exactor 2.2.4
  exjsx 4.0.0
  exvcr 0.10.0
  hackney 1.11.0
  httpoison 0.13.0
  idna 5.1.0
  jsx 2.8.3
  meck 0.8.9
  memoize 1.2.5
  metrics 1.0.1
  mimerl 1.0.2
  poison 3.1.0
  ssl_verify_fun 1.1.1
  unicode_util_compat 0.3.1
All dependencies up to date
Removing intermediate container e7cdf7f830a9
 ---> cc7d9ef44827
Step 8/8 : RUN mix test
 ---> Running in df578250894b
==> exactor
==> poison
==> exjsx
==> httpoison
==> exvcr
==> memoize
==> ifsc
Compiling 3 files (.ex)
Generated ifsc app
................

Finished in 2.2 seconds
16 tests, 0 failures
```

**Comment by nihalgonsalves** [comment]
@captn3m0 any update?

**Comment by captn3m0** [comment]
@nihalgonsalves tests are still failing. Wanna take a look?

<details>
<summary>build log</summary>

```


  1) test #validate should validate regular numeric branch codes (IFSCTest)
     tests/elixir/ifsc_test.exs:38
     match (=) failed
     code:  assert {:ok, %IFSC{}} = IFSC.validate("KKBK0000261")
     right: {:error, :enoent}
     stacktrace:
       tests/elixir/ifsc_test.exs:39: (test)



  2) test #validate should return the correct bank name and code for sublet branches (IFSCTest)
     tests/elixir/ifsc_test.exs:65
     match (=) failed
     code:  assert {:ok, %IFSC{bank: "Allahabad Up Gramin Bank", bank_code: "AUGX"}} = IFSC.validate("ALLA0AU1002")
     right: {:error, :enoent}
     stacktrace:
       tests/elixir/ifsc_test.exs:66: (test)



  3) test #validate should return the correct bank name and code for regular branches (IFSCTest)
     tests/elixir/ifsc_test.exs:58
     match (=) failed
     code:  assert {:ok, %IFSC{bank: "Kotak Mahindra Bank", bank_code: "KKBK"}} = IFSC.validate("KKBK0000261")
     right: {:error, :enoent}
     stacktrace:
       tests/elixir/ifsc_test.exs:59: (test)

.

  4) test #validate should validate string branch codes (IFSCTest)
     tests/elixir/ifsc_test.exs:45
     match (=) failed
     code:  assert {:ok, %IFSC{}} = IFSC.validate("BOTM0NEEMRA")
     right: {:error, :enoent}
     stacktrace:
       tests/elixir/ifsc_test.exs:46: (test)

..

  5) test acceptance testHPSC (IFSCAcceptanceTest)
     tests/elixir/ifsc_acceptance_test.exs:10
     match (=) failed
     code:  assert {:ok, %IFSC{}} = IFSC.validate(ifsc)
     right: {:error, :enoent}
     stacktrace:
       tests/elixir/ifsc_acceptance_test.exs:13: anonymous fn/1 in IFSCAcceptanceTest."test acceptance testHPSC"/1
       (elixir) lib/enum.ex:1298: anonymous fn/3 in Enum.map/2
       (stdlib) lists.erl:1263: :lists.foldl/3
       (elixir) lib/enum.ex:1915: Enum.map/2
       tests/elixir/ifsc_acceptance_test.exs:11: (test)



  6) test acceptance testValidateStringLookup (IFSCAcceptanceTest)
     tests/elixir/ifsc_acceptance_test.exs:10
     match (=) failed
     code:  assert {:ok, %IFSC{}} = IFSC.validate(ifsc)
     right: {:error, :enoent}
     stacktrace:
       tests/elixir/ifsc_acceptance_test.exs:13: anonymous fn/1 in IFSCAcceptanceTest."test acceptance testValidateStringLookup"/1
       (elixir) lib/enum.ex:1298: anonymous fn/3 in Enum.map/2
       (stdlib) lists.erl:1263: :lists.foldl/3
       (elixir) lib/enum.ex:1915: Enum.map/2
       tests/elixir/ifsc_acceptance_test.exs:11: (test)

.

  7) test acceptance testBasicValidator (IFSCAcceptanceTest)
     tests/elixir/ifsc_acceptance_test.exs:10
     match (=) failed
     code:  assert {:ok, %IFSC{}} = IFSC.validate(ifsc)
     right: {:error, :enoent}
     stacktrace:
       tests/elixir/ifsc_acceptance_test.exs:13: anonymous fn/1 in IFSCAcceptanceTest."test acceptance testBasicValidator"/1
       (elixir) lib/enum.ex:1298: anonymous fn/3 in Enum.map/2
       (stdlib) lists.erl:1263: :lists.foldl/3
       (elixir) lib/enum.ex:1915: Enum.map/2
       tests/elixir/ifsc_acceptance_test.exs:11: (test)



  8) test acceptance testNewSBICodes (IFSCAcceptanceTest)
     tests/elixir/ifsc_acceptance_test.exs:10
     match (=) failed
     code:  assert {:ok, %IFSC{}} = IFSC.validate(ifsc)
     right: {:error, :enoent}
     stacktrace:
       tests/elixir/ifsc_acceptance_test.exs:13: anonymous fn/1 in IFSCAcceptanceTest."test acceptance testNewSBICodes"/1
       (elixir) lib/enum.ex:1298: anonymous fn/3 in Enum.map/2
       (stdlib) lists.erl:1263: :lists.foldl/3
       (elixir) lib/enum.ex:1915: Enum.map/2
       tests/elixir/ifsc_acceptance_test.exs:11: (test)


```
</details>

**Comment by nihalgonsalves** [comment]
@captn3m0 The `:enoent`s are related to loading the JSON files. I'm still not sure what causes it to fail in Wercker, perhaps the working directory is incorrect? The same test command runs file otherwise. 

I tried running the Wercker CLI to debug it, but the build pipeline always fails at "Sheet Download complete, starting export"

**Comment by captn3m0** [comment]
You can try running `wercker build --pipeline elixir`. I rebased this branch against master and tried it and it worked:

```
wercker build --pipeline elixir
--> No Docker host specified, checking: /var/run/docker.sock
--> Executing pipeline
--> Running step: setup environment
Pulling from library/elixir: latest
Digest: sha256:d39d17457269581e582a5582950cf66f56f89e3bd54438a7d59431f504fdbc56
Status: Image is up to date for elixir:latest
--> Copying source to container
--> Running step: wercker-init
--> Running step: install hex
* creating /root/.mix/archives/hex-0.17.3
--> Running step: install rebar3
* creating /root/.mix/rebar
* creating /root/.mix/rebar3
--> Running step: get dependencies
Resolving Hex dependencies...
Dependency resolution completed:
  certifi 2.0.0
  earmark 1.2.4
  ex_doc 0.18.3
  exactor 2.2.4
  exjsx 4.0.0
  exvcr 0.10.0
  hackney 1.11.0
  httpoison 0.13.0
  idna 5.1.0
  jsx 2.8.3
  meck 0.8.9
  memoize 1.2.5
  metrics 1.0.1
  mimerl 1.0.2
  poison 3.1.0
  ssl_verify_fun 1.1.1
  unicode_util_compat 0.3.1
All dependencies up to date
--> Running step: run tests
..............

Finished in 1.8 seconds
14 tests, 0 failures

Randomized with seed 537417
--> Steps passed: 23.02s
--> Pipeline finished: 24.02s
```

**Comment by captn3m0** [comment]
I'm going to let the next release happen (hopefully by today) and then relook at this.

**Comment by nihalgonsalves** [comment]
You're right, it works perfectly locally. Any clue why it would differ from the online build?

**Comment by captn3m0** [comment]
The artifacts on the `build` step are passed to the `elixir` step, which might be causing issues. Is there any way to get a better stacktrace, this just points to the test failure instead of the actual file that is failing?

**Comment by nihalgonsalves** [comment]
Well all the errors originate from the same call here: https://github.com/razorpay/ifsc/blob/master/src/elixir/lib/razorpay/ifsc/data.ex#L49

The `mix test` command first copies the JSON files from `src` into `priv` so unless they are missing in `src` when the elixir pipeline begin execution, I can't think of what may cause this.

**Pull request closed without merging**
