### PR TITLE
5 seconds timeout

### PR DESCRIPTION
**Pull request by UJPrasad**

### CODE REVIEW

**Comment by UJPrasad** [comment]
Hi @captn3m0 can you please review this? We have seen a few instances where the request takes over 5 seconds.

**Comment by captn3m0** [comment]
Checking our metrics to decide on this.

**Comment by UJPrasad** [comment]
Hi, @captn3m0 any luck here?

**Comment by UJPrasad** [comment]
Hi @captn3m0 did you get time to check this?

**Comment by captn3m0** [comment]
The p99 for IFSC is under 300ms - this should never be taking 5 seconds. Planning to make this configurable regardless.

**Pull request closed without merging**
